// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $alllover from "./routes/alllover.tsx";
import * as $comment from "./routes/comment.tsx";
import * as $delete from "./routes/delete.tsx";
import * as $eliminarcoms from "./routes/eliminarcoms.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $profile from "./routes/profile.tsx";
import * as $register from "./routes/register.tsx";
import * as $bottonredirect from "./islands/bottonredirect.tsx";
import * as $comentar from "./islands/comentar.tsx";
import * as $formdelete from "./islands/formdelete.tsx";
import * as $formelimcoms from "./islands/formelimcoms.tsx";
import * as $formlog from "./islands/formlog.tsx";
import * as $formregister from "./islands/formregister.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/alllover.tsx": $alllover,
    "./routes/comment.tsx": $comment,
    "./routes/delete.tsx": $delete,
    "./routes/eliminarcoms.tsx": $eliminarcoms,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/profile.tsx": $profile,
    "./routes/register.tsx": $register,
  },
  islands: {
    "./islands/bottonredirect.tsx": $bottonredirect,
    "./islands/comentar.tsx": $comentar,
    "./islands/formdelete.tsx": $formdelete,
    "./islands/formelimcoms.tsx": $formelimcoms,
    "./islands/formlog.tsx": $formlog,
    "./islands/formregister.tsx": $formregister,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
